language: node_js
node_js:
  - 14

services:
  - docker

# Scripts to be run such as tests
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-api-frontend $DOCKER_USERNAME/udagram-api-frontend:v1
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v1

  
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-api-frontend:v1
  - docker push $DOCKER_USERNAME/reverseproxy:v1
