apiVersion: v1
kind: Service
metadata:
  name: backend-user-service-v1-0-0
  labels:
    app: backend-user-service
    version: v1.0.0
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: backend-user
    version: v1.0.0
