apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service-v1.0.0
  labels:
    app: backend-feed-service
    version: v1.0.0
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: backend-feed
    version: v1.0.0