apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  ports:
    - port: 8100
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
